# Generated by Django 4.1.7 on 2023-04-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_image_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
